import type { VerticalConfig } from './types';

export const adultServicesConfig: VerticalConfig = {
  id: 'adult_services',
  label: 'Adult Services',
  terminology: {
    staff: 'Worker',
    staff_plural: 'Workers',
    client: 'Client',
    client_plural: 'Clients',
    booking: 'Booking',
    booking_plural: 'Bookings',
    service_tag: 'Service',
    service_plural: 'Services',
    booking_notes_placeholder: 'Any special requests or notes...',
    operator: 'Agent',
  },
  defaults: {
    client_mode: 'account',
    booking_confirm_mode: 'staff_must_accept',
    client_approval_mode: 'manual',
    default_slot_minutes: 30,
    require_booking_notes: false,
    booking_notes_label: 'Notes',
    age_gate_minimum: 21,
    require_age_confirm: true,
    pricing_enabled: true,
  },
  show_kvk_field: true,
  show_license_field: true,
  show_bsn_on_staff: true,
  show_gdpr_photo_consent: true,
  show_age_gate_step: true,
  staff_require_pseudonym: true,
  seed_tags: ['Escort', 'Massage', 'GFE', 'Dinner Date'],
  deposits_supported: false,
};
