import type { VerticalConfig } from './types';

export const tattooConfig: VerticalConfig = {
  id: 'tattoo',
  label: 'Tattoo Studio',
  terminology: {
    staff: 'Artist',
    staff_plural: 'Artists',
    client: 'Client',
    client_plural: 'Clients',
    booking: 'Appointment',
    booking_plural: 'Appointments',
    service_tag: 'Style',
    service_plural: 'Styles',
    booking_notes_placeholder: 'Describe the tattoo you have in mind — style, size, placement, reference images...',
    operator: 'Manager',
  },
  defaults: {
    client_mode: 'guest',
    booking_confirm_mode: 'staff_must_accept',
    client_approval_mode: 'auto',
    default_slot_minutes: 60,
    require_booking_notes: true,
    booking_notes_label: 'Describe your piece (style, placement, size, references)',
    age_gate_minimum: 18,
    require_age_confirm: true,
    pricing_enabled: true,
  },
  show_kvk_field: false,
  show_license_field: false,
  show_bsn_on_staff: false,
  show_gdpr_photo_consent: true,
  show_age_gate_step: true,
  staff_require_pseudonym: false,
  seed_tags: [
    'Black & Grey',
    'Realism',
    'Traditional',
    'Neo-Traditional',
    'Japanese',
    'Geometric',
    'Watercolour',
    'Minimalist',
    'Lettering',
    'Cover-Up',
    'Flash',
  ],
  deposits_supported: true,
};
