services:
  bookit-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookit-frontend
    restart: unless-stopped
    env_file:
      - .env.production
    networks:
      - web

networks:
  web:
    external: true
