services:
  bookit:
    build: .
    container_name: bookit
    restart: unless-stopped
    ports:
      - "3020:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      ENABLE_CRON: "true"
    networks:
      - proxy
      - bookit-network

networks:
  bookit-network:
    driver: bridge
  proxy:
    external: true
